"""Add SMTP configurations to AppConfig

Revision ID: 12eaed1e39ae
Revises: 48fc51286599
Create Date: 2026-03-28 19:30:23.168482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12eaed1e39ae'
down_revision = '48fc51286599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_server', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smtp_user', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('smtp_password', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('smtp_use_tls', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('smtp_use_ssl', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mail_sender_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('mail_sender_name')
        batch_op.drop_column('smtp_use_ssl')
        batch_op.drop_column('smtp_use_tls')
        batch_op.drop_column('smtp_password')
        batch_op.drop_column('smtp_user')
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_server')

    # ### end Alembic commands ###
