"""add navbar colors to appconfig

Revision ID: 13983bf3686d
Revises: 6a2f4e4f66f7
Create Date: 2026-03-27 17:51:34.291189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13983bf3686d'
down_revision = '6a2f4e4f66f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('navbar_bg_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('navbar_link_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('navbar_link_color')
        batch_op.drop_column('navbar_bg_color')

    # ### end Alembic commands ###
