"""add navbar_hover_color to appconfig

Revision ID: 48fc51286599
Revises: 53f86f007e2c
Create Date: 2026-03-27 20:33:15.953627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fc51286599'
down_revision = '53f86f007e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('navbar_hover_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('navbar_hover_color')

    # ### end Alembic commands ###
