"""add service instructions parts and code

Revision ID: 53cdd6742b47
Revises: d7b2f4a6c1e9
Create Date: 2026-04-16 18:51:08.159835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cdd6742b47'
down_revision = 'd7b2f4a6c1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('service_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_catalog', schema=None) as batch_op:
        batch_op.drop_column('service_code')
        batch_op.drop_column('parts')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
