"""add permission_level and job_title

Revision ID: 53f86f007e2c
Revises: aab17e8f7e5a
Create Date: 2026-03-27 20:15:26.827960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision = '53f86f007e2c'
down_revision = 'aab17e8f7e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_level', sa.String(length=20), server_default='user', nullable=False))
        batch_op.add_column(sa.Column('job_title', sa.String(length=50), server_default='Técnico', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('job_title')
        batch_op.drop_column('permission_level')

    # ### end Alembic commands ###
