"""Add smtp_provider to AppConfig

Revision ID: 88f474af94f1
Revises: 12eaed1e39ae
Create Date: 2026-03-28 19:52:15.714580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f474af94f1'
down_revision = '12eaed1e39ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_provider', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('smtp_provider')

    # ### end Alembic commands ###
