"""add qr_code_path to equipment

Revision ID: aab17e8f7e5a
Revises: 13983bf3686d
Create Date: 2026-03-27 18:56:22.731221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab17e8f7e5a'
down_revision = '13983bf3686d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('qr_code_path')

    # ### end Alembic commands ###
