"""Add financial module models

Revision ID: cafd02fb47b0
Revises: f1a2b3c4d5e6
Create Date: 2026-04-19 09:21:34.593837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafd02fb47b0'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'financial_category' not in tables:
        op.create_table('financial_category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'financial_transaction' not in tables:
        op.create_table('financial_transaction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('work_order_id', sa.Integer(), nullable=True),
        sa.Column('work_order_expense_id', sa.Integer(), nullable=True),
        sa.Column('is_automated', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['financial_category.id'], ),
        sa.ForeignKeyConstraint(['work_order_expense_id'], ['workorder_expense.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_transaction')
    op.drop_table('financial_category')
    # ### end Alembic commands ###
