"""add cnpj to appconfig

Revision ID: e7bcf82d1c92
Revises: 53cdd6742b47
Create Date: 2026-04-17 10:41:30.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7bcf82d1c92'
down_revision = '53cdd6742b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###
