"""add user fields

Revision ID: e851571e38a7
Revises: c9a3fd93c9c5
Create Date: 2026-04-30 09:49:42.786697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e851571e38a7'
down_revision = 'c9a3fd93c9c5'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    if is_sqlite:
        op.execute('PRAGMA foreign_keys=OFF')
        
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_user_cpf', ['cpf'])

    # ### end Alembic commands ###
    if is_sqlite:
        op.execute('PRAGMA foreign_keys=ON')


def downgrade():
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    
    if is_sqlite:
        op.execute('PRAGMA foreign_keys=OFF')
        
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_cpf', type_='unique')
        batch_op.drop_column('phone')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
    if is_sqlite:
        op.execute('PRAGMA foreign_keys=ON')
