"""Add maintenance interval and photos to WO

Revision ID: f28f3b783c81
Revises: 88f474af94f1
Create Date: 2026-04-03 21:21:02.221105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28f3b783c81'
down_revision = '88f474af94f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_interval', sa.Integer(), nullable=True))

    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_before', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo_after', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_column('photo_after')
        batch_op.drop_column('photo_before')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('maintenance_interval')

    # ### end Alembic commands ###
